### ISSUE TITLE
Infrastructure Handover

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/goobi-infrastructure#234]
In order that Goobi infrastructure receives the necessary attention it should be maintainable by Intranda. 

As part of this we should:

- [x] Document existing architecture in intranda Gitbook #248 
- [x] Copy modules from terraform-modules to local #262 
- [x] Update terraform to post 0.12 #264
- [x] Create a usable staging environment  #265

These **should have their own issue** when work starts on them.

**Comment by mgeerdsen** [comment]
Still a lot of things to be improved over time, but with the staging environment being available this can be closed.
