### ISSUE TITLE
check processes with steps in error for possible automatical/simple fixes

### ISSUE THREAD

**Issue by mgeerdsen** [wellcomecollection/goobi-infrastructure#292]
Goobi workflow filter expression: `steperror:`

- [ ] failed jpylzer validation #291 
- [ ] failed ALTO step #290 
- [ ] error in ingest/callback #288
